site:
  name: Stone
  link: https://stone.reaper.im
  description: CSS-IN-JS Framework

template_names:
  post_template: "blogPostHTML"
  post_index_template: "blogIndexHTML"
  page_template: "simplePageHTML"
  rss_template: "rssTemplate"

content_path: "./content"
templates_path: "./templates"
out_path: "./out"
public_folder: "./public"
generate_rss: true
rss_out_path: "./out/blog.xml"
